### ISSUE TITLE
Dockerizing

### ISSUE THREAD

**Issue by diamondburned** [slepe/ModernMemoryAlloc#1]
Can this library be Dockerized? As we move towards 2021, we need more libraries that are at enterprise-scale. It would be great if this library has a Java binding as well as a Dockerfile.

**Comment by slepe** [comment]
Please use the [ISSUE TEMPLATE](https://github.com/slepe/ModernMemoryAlloc/blob/master/PULLREQUESTTEMPLATE.md)
